docker-library/postgres

- 8.4/docker-entrypoint.sh
- 9.0/docker-entrypoint.sh
- 9.1/docker-entrypoint.sh
- 9.2/docker-entrypoint.sh
- 9.3/docker-entrypoint.sh
- 9.4/docker-entrypoint.sh
- docker-entrypoint.sh
This makes it so that it no longer blocks on username.  If no `POSTGRES_PASSWORD` is specified it will be very insecure (`trust` any user from anywhere), otherwise it will have `md5` as the auth method.
Fixes: #47
Related: #31
> Update pg_hba generation

- 8.4/docker-entrypoint.sh
- 9.0/docker-entrypoint.sh
- 9.1/docker-entrypoint.sh
- 9.2/docker-entrypoint.sh
- 9.3/docker-entrypoint.sh
- 9.4/docker-entrypoint.sh
- docker-entrypoint.sh
POSTGRESS_DB defaults to POSTGRESS_USER if it's not specified.
Example run
```
docker run -d --name postgres -e POSTGRES_DB=testdb -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=password postgres
```
You can also connect to the db with
```
docker run --rm -it --name dbconnect --link postgres:db postgres sh -c 'exec psql -h "$DB_PORT_5432_TCP_ADDR" -p "$DB_PORT_5432_TCP_PORT" -d testdb -U postgres'
```
> Added POSTGRES_DB variable to optionally specify DB name

- 8.4/Dockerfile
- 9.0/Dockerfile
- 9.1/Dockerfile
- 9.2/Dockerfile
- 9.3/Dockerfile
- 9.4/Dockerfile
- Dockerfile.template
- move to "high-availability" [subset](https://sks-keyservers.net/overview-of-pools.php#pool_ha).
related: https://github.com/docker-library/php/pull/92
> More resilient gpg getting

- 9.0/docker-entrypoint.sh
- 9.1/docker-entrypoint.sh
- 9.2/docker-entrypoint.sh
- 9.3/docker-entrypoint.sh
- 9.4/docker-entrypoint.sh
- 9.5/docker-entrypoint.sh
- docker-entrypoint.sh
Part of fix for mounting persistent disks on Google Cloud Compute containers - fresh disks have a `lost+found` directory, causing the old check to fail with 
```
postgres cannot access the server configuration file "/var/lib/postgresql/data/postgresql.conf"
```
The second part of the fix requires the GCE user to adjust `PGDATA` to a subdirectory within the mounted persistent disk. If the `initdb` command is run directly on the mount point root, it fails, complaining that it is bad practice to have the database there. [Reference thread](http://postgresql.nabble.com/src-ports-pgcheckdir-c-Ignore-dot-directories-td5743755.html).
The notice to adjust `PGDATA` should be in the docs for postgres-docker.
I feel we should not make it mandatory for `PGDATA` to auto-create a subdirectory at all …
> Check that vol actually contains DB files, as opposed to a non-empty dir.

- 9.0/Dockerfile
- 9.1/Dockerfile
- 9.2/Dockerfile
- 9.3/Dockerfile
- 9.4/Dockerfile
- 9.5/Dockerfile
- Dockerfile.template
There are several (10) packages that "curl" pulls in which are then never removed -- "wget" does not have this problem.
> Switch from curl to wget

- 9.0/docker-entrypoint.sh
- 9.1/docker-entrypoint.sh
- 9.2/docker-entrypoint.sh
- 9.3/docker-entrypoint.sh
- 9.4/docker-entrypoint.sh
- 9.5/docker-entrypoint.sh
- docker-entrypoint.sh
`postgres --single` already has a lot of quirks, but is also discouraged for use by upstream (although why that fact isn't included prominently in the documentation for single-user mode, I have no idea -- it seems like an important bit to point out).
This mimics the server startup logic in https://github.com/docker-library/mysql/pull/53 to give us "proper" PostgreSQL server access, while also setting `listen_addresses` to the empty string to prevent remote connections during our initialization process.
> Improve initdb logic to properly source *.sql files as well, without the use of --single

- docker-entrypoint.sh
as recommended per postgresql docs and implemented according to http://stackoverflow.com/questions/28244869/creating-a-table-in-single-user-mode-in-postgres
The -w option of pg_ctl waits until server is started or stopped. This avoids the 30 second countdown and repeatedly querying database.
> more sane way of starting and stopping postgres server using pg_ctl

- 9.0/docker-entrypoint.sh
- 9.1/docker-entrypoint.sh
- 9.2/docker-entrypoint.sh
- 9.3/docker-entrypoint.sh
- 9.4/docker-entrypoint.sh
- 9.5/docker-entrypoint.sh
- docker-entrypoint.sh
This PR changes the entrypoint to run any `/docker-entrypoint-initdb.d/*.sql` scripts as `$POSTGRES_USER`. Previously, the scripts were always run as `postgres` (which is the default for `$POSTGRES_USER`, so nothing changes in the default case).
Since `$POSTGRES_USER` is given `SUPERUSER` privileges in the entrypoint, that user should be able to do anything `postgres` can do. I tested having it create a database and a role, both of which worked despite the fact that `CREATEDB` and `CREATEROLE` are not granted explicitly.
Fixes #81
> Run /docker-entrypoint-initdb.d/*.sql scripts as $POSTGRES_USER

- 9.0/docker-entrypoint.sh
- 9.1/docker-entrypoint.sh
- 9.2/docker-entrypoint.sh
- 9.3/docker-entrypoint.sh
- 9.4/docker-entrypoint.sh
- 9.5/docker-entrypoint.sh
- docker-entrypoint.sh
As it now stands the `$POSTGRES_USER` and `$POSTGRES_DB` variables aren't visible in `/docker-entrypoint-initdb.d/*.sh` scripts unless they have been set explicitly with `-e` in the `docker run` command or with `ENV` in a derived `Dockerfile`.
This change allows those variables to be seen in the `*.sh` scripts. Without this change, any `*.sh` scripts that want to follow the same conventions as the `postgres` base image need to duplicate this code:
```bash
: ${POSTGRES_USER:=postgres}
: ${POSTGRES_DB:=$POSTGRES_USER}
```
I ran into this while trying to implement https://github.com/appropriate/docker-postgis/issues/4 (*Enable PostGIS extensions on default database*).
> Export POSTGRES_USER and POSTGRES_DB vars in entrypoint

- 9.0/Dockerfile
- 9.1/Dockerfile
- 9.2/Dockerfile
- 9.3/Dockerfile
- 9.4/Dockerfile
- 9.5/Dockerfile
The values 999:999 are identical to the current user/group id assigned
in the containers (tested in postgres:9.4, but should be identical for
all versions), but this guarantees that those values will remain the
same even if the `groupadd`/`useradd` commands were moved elsewhere in the
Dockerfile, or a new version of `debian:jessie` image was pushed.
```
core@test-1 ~ $ rm -rf pg/
core@test-1 ~ $ docker run -v $(pwd):/origin --rm -it --user=root postgres:9.4 bash -c 'mkdir /origin/pg && chown -R postgres:postgres /origin/pg'
core@test-1 ~ $ ls -hsal pg/
total 8.0K
4.0K drwxr-xr-x 2  999  999 4.0K Sep 22 12:59 .
4.0K drwxr-xr-x 5 core core 4.0K Sep 22 12:59 ..
```
```
core@test-1 ~ $ docker run -v $(pwd):/origin --rm -it debian:jessie bash -c 'groupadd -r postgres --gid=999 && useradd -r -g …
```
> Explicitly set uid/gid for postgres/postgres

- 9.0/docker-entrypoint.sh
- 9.1/docker-entrypoint.sh
- 9.2/docker-entrypoint.sh
- 9.3/docker-entrypoint.sh
- 9.4/docker-entrypoint.sh
- 9.5/docker-entrypoint.sh
- docker-entrypoint.sh
When mounting a volume to PGDATA, it may not have permissions set to 700 which causes postgres to fail with:
```
FATAL:  data directory "/var/lib/postgresql/data" has group or world access
Permissions should be u=rwx (0700).
```
To fix this, we can explicitly set it to 700 like we do with the owner.
> Set PGDATA permissions to 700

- 9.0/Dockerfile
- 9.1/Dockerfile
- 9.2/Dockerfile
- 9.3/Dockerfile
- 9.4/Dockerfile
- 9.5/Dockerfile
- Dockerfile.template
this keyserver is either not reachable anymore or there is any firewall between blocking the connection
```bash
root@c3e344cb9cca:/# gpg --keyserver pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4                                                                                                                                                     
gpg: directory `/root/.gnupg' created
gpg: new configuration file `/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/root/.gnupg/secring.gpg' created
gpg: keyring `/root/.gnupg/pubring.gpg' created
gpg: requesting key BF357DD4 from hkp server pool.sks-keyservers.net
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error
``` …
> use the keyserver ha, because the other one is not reachable anymore

- 9.1/Dockerfile
- 9.2/Dockerfile
- 9.3/Dockerfile
- 9.4/Dockerfile
- 9.5/Dockerfile
Ran into issue today with `9.4.5-2.pgdg80+1` not being a thing anymore so figured it should be updated along with the rest :innocent:
> Version updates

- 9.1/Dockerfile
- 9.1/docker-entrypoint.sh
- 9.2/Dockerfile
- 9.2/docker-entrypoint.sh
- 9.3/Dockerfile
- 9.3/docker-entrypoint.sh
- 9.4/Dockerfile
- 9.4/docker-entrypoint.sh
- 9.5/Dockerfile
- 9.5/docker-entrypoint.sh
- Dockerfile.template
- docker-entrypoint.sh
Closes #120
Fixes #105
Closes #54
(needs documentation updates too)
> Refactor listen_addresses to be set in the sample file, and make the sample file easier to overwrite

- 9.1/docker-entrypoint.sh
- 9.2/docker-entrypoint.sh
- 9.3/docker-entrypoint.sh
- 9.4/docker-entrypoint.sh
- 9.5/docker-entrypoint.sh
- docker-entrypoint.sh
This closes #19 per @tianon's [suggestion](https://github.com/docker-library/postgres/issues/19#issuecomment-58397184).
```
$ docker run --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -e POSTGRES_INITDB_ARGS="--data-checksums" --rm postgres
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.
The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".
Data page checksums are enabled.
...
```
> Add POSTGRES_INITDB_ARGS env var

- 9.1/docker-entrypoint.sh
- 9.2/docker-entrypoint.sh
- 9.3/docker-entrypoint.sh
- 9.4/docker-entrypoint.sh
- 9.5/docker-entrypoint.sh
- docker-entrypoint.sh
Fixes #129
http://www.postgresql.org/docs/9.1/static/runtime-config-connection.html
> The default value is localhost, which allows only local TCP/IP "loopback" connections to be made.
This allows for crappy broken drivers that don't support Unix sockets to be usable during initdb.
> Listen on "local" interfaces during init

- 9.1/docker-entrypoint.sh
- 9.2/docker-entrypoint.sh
- 9.3/docker-entrypoint.sh
- 9.4/docker-entrypoint.sh
- 9.5/docker-entrypoint.sh
- 9.6/docker-entrypoint.sh
- docker-entrypoint.sh
This allows the container to run with a tmpfs /run.
It seems like this is the only change that is needed to run this image read-only with a tmpfs /run and /tmp but I need to test it more.
> Add "mkdir -p /run/postgresql" to docker-entrypoint.sh.

- 9.2/alpine/docker-entrypoint.sh
- 9.2/docker-entrypoint.sh
- 9.3/alpine/docker-entrypoint.sh
- 9.3/docker-entrypoint.sh
- 9.4/alpine/docker-entrypoint.sh
- 9.4/docker-entrypoint.sh
- 9.5/alpine/docker-entrypoint.sh
- 9.5/docker-entrypoint.sh
- 9.6/alpine/docker-entrypoint.sh
- 9.6/docker-entrypoint.sh
- docker-entrypoint.sh
This adds explicit support for the following:
- `POSTGRES_DB_FILE`
- `POSTGRES_INITDB_ARGS_FILE`
- `POSTGRES_PASSWORD_FILE`
- `POSTGRES_USER_FILE`
See also https://github.com/docker-library/wordpress/pull/186
> Add "file_env" support, especially for Docker secrets

- 9.2/alpine/Dockerfile
- 9.3/alpine/Dockerfile
- 9.4/alpine/Dockerfile
- 9.5/alpine/Dockerfile
- 9.6/alpine/Dockerfile
- Dockerfile-alpine.template
See #220 for discussion.
Fixes #227
> Add missing timezone info to alpine variant

- 9.2/alpine/docker-entrypoint.sh
- 9.2/docker-entrypoint.sh
- 9.3/alpine/docker-entrypoint.sh
- 9.3/docker-entrypoint.sh
- 9.4/alpine/docker-entrypoint.sh
- 9.4/docker-entrypoint.sh
- 9.5/alpine/docker-entrypoint.sh
- 9.5/docker-entrypoint.sh
- 9.6/alpine/docker-entrypoint.sh
- 9.6/docker-entrypoint.sh
- docker-entrypoint.sh
IPv6 default rule added into pg_hba.conf
> Update generated "pg_hba.conf" content for IPv6 support

- 9.2/alpine/docker-entrypoint.sh
- 9.2/docker-entrypoint.sh
- 9.3/alpine/docker-entrypoint.sh
- 9.3/docker-entrypoint.sh
- 9.4/alpine/docker-entrypoint.sh
- 9.4/docker-entrypoint.sh
- 9.5/alpine/docker-entrypoint.sh
- 9.5/docker-entrypoint.sh
- 9.6/alpine/docker-entrypoint.sh
- 9.6/docker-entrypoint.sh
- docker-entrypoint.sh
Doing it like this, allows one to use \ir command and have files in a directory structure instead of a single top level dir.
> Use -f flag when executing sql scripts (fix #231)

- 9.2/alpine/Dockerfile
- 9.3/alpine/Dockerfile
- 9.4/alpine/Dockerfile
- 9.5/alpine/Dockerfile
- 9.6/alpine/Dockerfile
- Dockerfile-alpine.template
Fixes #241
```
postgres  9.6-alpine-after    83c9edfc60a1        2 minutes ago       32.53 MB
postgres  9.6-alpine-before   56409b6ffc83        9 minutes ago       49.43 MB
```
> Remove "doc" and "man" from Alpine images for size

- 9.2/Dockerfile
- 9.3/Dockerfile
- 9.4/Dockerfile
- 9.5/Dockerfile
- 9.6/Dockerfile
- Dockerfile-debian.template
> Note: Instead of using this command a keyring should be placed
> directly in the /etc/apt/trusted.gpg.d/ directory with a
> descriptive name and either "gpg" or "asc" as file extension.
https://manpages.debian.org/cgi-bin/man.cgi?query=apt-key&manpath=Debian+testing+stretch
See also docker-library/cassandra#91, docker-library/mariadb#93, docker-library/mongo#132, docker-library/mysql#254, and https://github.com/docker-library/percona/pull/39.
> Use "/etc/apt/trusted.gpg.d" instead of "apt-key adv"

- 9.2/Dockerfile
- 9.2/alpine/Dockerfile
- 9.2/alpine/docker-entrypoint.sh
- 9.2/docker-entrypoint.sh
- 9.3/Dockerfile
- 9.3/alpine/Dockerfile
- 9.3/alpine/docker-entrypoint.sh
- 9.3/docker-entrypoint.sh
- 9.4/Dockerfile
- 9.4/alpine/Dockerfile
- 9.4/alpine/docker-entrypoint.sh
- 9.4/docker-entrypoint.sh
- 9.5/Dockerfile
- 9.5/alpine/Dockerfile
- 9.5/alpine/docker-entrypoint.sh
- 9.5/docker-entrypoint.sh
- 9.6/Dockerfile
- 9.6/alpine/Dockerfile
- 9.6/alpine/docker-entrypoint.sh
- 9.6/docker-entrypoint.sh
- Dockerfile-alpine.template
- Dockerfile-debian.template
- docker-entrypoint.sh
One special case is that `initdb` _requires_ the current user to exist in `/etc/passwd`, but running PostgreSQL itself does not require that.
As discussed over in https://github.com/docker-library/postgres/pull/93#issuecomment-273877372.
See also docker-library/rabbitmq#60, docker-library/cassandra#48, docker-library/mongo#81, docker-library/redis#48, docker-library/mysql#161, docker-library/mariadb#59, docker-library/percona#21, and https://github.com/docker-library/ghost/pull/54.
Closes #46
Closes #116
Closes #206
Closes #251
Ref #28
> Allow arbitrary --user values (mostly)

- 9.2/alpine/Dockerfile
- 9.3/alpine/Dockerfile
- 9.4/alpine/Dockerfile
- 9.5/alpine/Dockerfile
- 9.6/alpine/Dockerfile
- Dockerfile-alpine.template
Unless there's a way to only install the source headers from the postgres source, it's impossible to use this image as a base image for postgis because they are missing. It only adds 3 MB of data to the image to keep them: 
```
REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE
postgres               test                136c6c4d4782        10 minutes ago      35.3 MB
postgres               9.3-alpine          7c9bad9f1e8f        9 days ago          32.2 MB
```
> Keep lib sources so the image can be used as a base image for postgis

- 9.2/Dockerfile
- 9.2/alpine/Dockerfile
- 9.3/Dockerfile
- 9.3/alpine/Dockerfile
- 9.4/Dockerfile
- 9.4/alpine/Dockerfile
- 9.5/Dockerfile
- 9.5/alpine/Dockerfile
- 9.6/Dockerfile
- 9.6/alpine/Dockerfile
- Dockerfile-alpine.template
- Dockerfile-debian.template
This is generally nicer, but should also help with silly AUFS bugs:
```
Step 14 : COPY docker-entrypoint.sh /
stat /var/lib/docker/aufs/mnt/0ec6dc46d8c087f3570abbfbe62f67f3ecf80960dc0743d618482f692e6dc517/docker-entrypoint.sh: no such file or directory
```
> Put "docker-entrypoint.sh" in PATH (with backwards-compat symlink)

- 9.2/alpine/Dockerfile
- 9.3/alpine/Dockerfile
- 9.4/alpine/Dockerfile
- 9.5/alpine/Dockerfile
- 9.6/alpine/Dockerfile
- Dockerfile-alpine.template
- ossp-uuid.template
- update.sh
The 9.3 alpine image builds postgres with all the extensions (`make install-world`) but it's missing `--with-ossp-uuid`.
Just adding it is not enough because it seems like `uuid.h` from `util-linux-dev` doesn't satisfy the check for `libuuid`, it's looking for `uuid_export` which isn't present in that version of `uuid.h`.
```
checking for uuid_export in -lossp-uuid... no
checking for uuid_export in -luuid... no
configure: error: library 'ossp-uuid' or 'uuid' is required for OSSP-UUID
``` 
Because of this, I added ossp-uuid to the image. I had to use a mirror because the official ftp server is not reliable (it often fails with `CONNECTION_REFUSED`).
It also doesn't increase the size of the image significantly (+0.2 MB).
```
REPOSITORY                  TAG                           IMAGE ID …
```
> Add ossp uuid to the alpine 9.2 and 9.3 images

- 9.2/alpine/docker-entrypoint.sh
- 9.2/docker-entrypoint.sh
- 9.3/alpine/docker-entrypoint.sh
- 9.3/docker-entrypoint.sh
- 9.4/alpine/docker-entrypoint.sh
- 9.4/docker-entrypoint.sh
- 9.5/alpine/docker-entrypoint.sh
- 9.5/docker-entrypoint.sh
- 9.6/alpine/docker-entrypoint.sh
- 9.6/docker-entrypoint.sh
- docker-entrypoint.sh
Adds support for the POSTGRES_XLOG_DIR environment variable, which specifies where the postgres transaction log is stored.
For some use cases, being able to place the transaction log on a different volume is useful.
(Existing support for providing flags via $POSTGRES_INITDB_ARGS is inadequate because of the need to create and chown/chmod the directory prior to running initdb)
> POSTGRES_XLOG_DIR to specify transaction log dir

- 9.2/alpine/Dockerfile
- 9.2/alpine/docker-entrypoint.sh
- 9.2/docker-entrypoint.sh
- 9.3/alpine/Dockerfile
- 9.3/alpine/docker-entrypoint.sh
- 9.3/docker-entrypoint.sh
- 9.4/alpine/Dockerfile
- 9.4/alpine/docker-entrypoint.sh
- 9.4/docker-entrypoint.sh
- 9.5/alpine/Dockerfile
- 9.5/alpine/docker-entrypoint.sh
- 9.5/docker-entrypoint.sh
- 9.6/alpine/Dockerfile
- 9.6/alpine/docker-entrypoint.sh
- 9.6/docker-entrypoint.sh
- Dockerfile-alpine.template
- docker-entrypoint.sh
- ossp-uuid.template
This is along the same lines as:
- https://github.com/docker-library/python/pull/198
- https://github.com/docker-library/ruby/pull/127
- https://github.com/docker-library/tomcat/pull/70
- https://github.com/docker-library/memcached/pull/13
- https://github.com/tianon/docker-bash/pull/3
> Add explicit "--build" to our "./configure" invocations

- 9.2/Dockerfile
- 9.2/alpine/Dockerfile
- 9.2/alpine/docker-entrypoint.sh
- 9.2/docker-entrypoint.sh
- 9.3/Dockerfile
- 9.3/alpine/Dockerfile
- 9.3/alpine/docker-entrypoint.sh
- 9.3/docker-entrypoint.sh
- 9.4/Dockerfile
- 9.4/alpine/Dockerfile
- 9.4/alpine/docker-entrypoint.sh
- 9.4/docker-entrypoint.sh
- 9.5/Dockerfile
- 9.5/alpine/Dockerfile
- 9.5/alpine/docker-entrypoint.sh
- 9.5/docker-entrypoint.sh
- 9.6/Dockerfile
- 9.6/alpine/Dockerfile
- 9.6/alpine/docker-entrypoint.sh
- 9.6/docker-entrypoint.sh
- Dockerfile-alpine.template
- Dockerfile-debian.template
- docker-entrypoint.sh
- update.sh
Fixes #264
Before:
```console
$ rm -rf ~/wtf && mkdir -p ~/wtf && docker run -it --rm --name test --user "$(id -u):$(id -g)" -v /etc/passwd:/etc/passwd:ro -v "$HOME/wtf":/var/lib/postgresql/data postgres:9.6
The files belonging to this database system will be owned by user "tianon".
This user must also own the server process.
The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".
Data page checksums are disabled.
fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... …
```
> Adjust "/var/run/postgresql" permissions for arbitrary-user support

- .travis.yml
- 10/Dockerfile
- 10/alpine/Dockerfile
- 10/alpine/docker-entrypoint.sh
- 10/docker-entrypoint.sh
- 9.2/Dockerfile
- 9.2/alpine/Dockerfile
- 9.3/Dockerfile
- 9.3/alpine/Dockerfile
- 9.4/Dockerfile
- 9.4/alpine/Dockerfile
- 9.5/Dockerfile
- 9.5/alpine/Dockerfile
- 9.6/Dockerfile
- 9.6/alpine/Dockerfile
- Dockerfile-alpine.template
- Dockerfile-debian.template
- update.sh
Fixes #293
Also bump `jessie` to `stretch` and alpine `3.5` to `3.6` for postgres 10. We can discuss separately the bumping of other versions of postgres to `stretch` or `3.6`.
```diff
diff --git a/9.6/Dockerfile b/10/Dockerfile
index 4d13096..e5fca3b 100644
--- a/9.6/Dockerfile
+++ b/10/Dockerfile
@@ -1,5 +1,5 @@
-FROM debian:jessie
+FROM debian:stretch
RUN groupadd -r postgres --gid=999 && useradd -r -g postgres --uid=999 postgres
@@ -36,8 +36,8 @@ RUN set -ex; \
rm -r "$GNUPGHOME"; \
apt-key list
-ENV PG_MAJOR 9.6
-ENV PG_VERSION 9.6.3-1.pgdg80+1
+ENV PG_MAJOR 10
+ENV PG_VERSION 10~beta1-1.pgdg90+1
RUN echo 'deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main' $PG_MAJOR > /etc/apt/sources.list.d/pgdg.list
diff --git a/9.6/alpine/Dockerfile b/10/alpine/Dockerfile
index …
```
> Add 10~beta1

- 10/Dockerfile
- 10/alpine/Dockerfile
- 9.2/alpine/Dockerfile
- 9.3/alpine/Dockerfile
- 9.4/alpine/Dockerfile
- 9.5/alpine/Dockerfile
- 9.6/alpine/Dockerfile
- Dockerfile-alpine.template
This adds perl-ipc-run to Alpine since 10's configure script now requires it.
> Update to 10beta2

- 10/alpine/Dockerfile
- 9.2/alpine/Dockerfile
- 9.3/alpine/Dockerfile
- 9.4/alpine/Dockerfile
- 9.5/alpine/Dockerfile
- 9.6/alpine/Dockerfile
- Dockerfile-alpine.template
Copying the improvement from https://github.com/docker-library/ruby/pull/161.  Should be no discernible change in packages installed, but does make the sub-shell a little easier to understand.
> Adjust scanelf to properly detect runDeps

- 10/alpine/docker-entrypoint.sh
- 10/docker-entrypoint.sh
- docker-entrypoint.sh
- update.sh
Fixes #372
See also: https://wiki.postgresql.org/wiki/New_in_postgres_10#Renaming_of_.22xlog.22_to_.22wal.22_Globally_.28and_location.2Flsn.29
> Postgres 10 renamed xlog to wal

- 10/alpine/docker-entrypoint.sh
- 10/docker-entrypoint.sh
- 9.3/alpine/docker-entrypoint.sh
- 9.3/docker-entrypoint.sh
- 9.4/alpine/docker-entrypoint.sh
- 9.4/docker-entrypoint.sh
- 9.5/alpine/docker-entrypoint.sh
- 9.5/docker-entrypoint.sh
- 9.6/alpine/docker-entrypoint.sh
- 9.6/docker-entrypoint.sh
Healthchecks that used `pg_isready -p 5432` were incorrectly flagging
the container as being healthy during initialization phase since
healthchecks are being run inside the container itself, so
`listen_addresses='localhost'` was not enough. The port `65432` was
chosen at random.
> Listen only on the unix socket during init 

- 10/Dockerfile
- 10/alpine/docker-entrypoint.sh
- 10/docker-entrypoint.sh
- 9.3/Dockerfile
- 9.3/alpine/docker-entrypoint.sh
- 9.3/docker-entrypoint.sh
- 9.4/Dockerfile
- 9.4/alpine/docker-entrypoint.sh
- 9.4/docker-entrypoint.sh
- 9.5/Dockerfile
- 9.5/alpine/docker-entrypoint.sh
- 9.5/docker-entrypoint.sh
- 9.6/Dockerfile
- 9.6/alpine/docker-entrypoint.sh
- 9.6/docker-entrypoint.sh
- Dockerfile-debian.template
- docker-entrypoint.sh
Closes #359
```console
$ docker build 10
...
Successfully built 8808cf28be91
$ mkdir "$HOME/pgtemp"
$ sudo chown 1000:1000 "$HOME/pgtemp"
$ docker run -it --rm --user 1000:1000 -v "$HOME/pgtemp":/var/lib/postgresql/data 8808cf28be91
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.
The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".
Data page checksums are disabled.
fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared …
```
> Implement "nss_wrapper" for Debian variants

- 10/alpine/docker-entrypoint.sh
- 10/docker-entrypoint.sh
- 11/alpine/docker-entrypoint.sh
- 11/docker-entrypoint.sh
- 9.3/alpine/docker-entrypoint.sh
- 9.3/docker-entrypoint.sh
- 9.4/alpine/docker-entrypoint.sh
- 9.4/docker-entrypoint.sh
- 9.5/alpine/docker-entrypoint.sh
- 9.5/docker-entrypoint.sh
- 9.6/alpine/docker-entrypoint.sh
- 9.6/docker-entrypoint.sh
- docker-entrypoint.sh
Closes #450
cc @willglynn (is this similar to the workaround you've applied in your own scripts?)
> Allow "initdb.d" scripts to be executed instead of sourced

- .travis.yml
- 10/Dockerfile
- 11/Dockerfile
- 9.3/Dockerfile
- 9.4/Dockerfile
- 9.5/Dockerfile
- 9.6/Dockerfile
- Dockerfile-debian.template
Refs https://github.com/docker-library/php/pull/666
> Add "pgp-happy-eyeballs" in Travis to help cut down on gpg-related issues

- 10/alpine/Dockerfile
- 11/alpine/Dockerfile
- Dockerfile-alpine.template
- update.sh
This builds PostgreSQL with the ICU collation provider:
https://www.postgresql.org/docs/10/static/collation.html
> Build with the ICU collation provider

- 10/Dockerfile
- 11/Dockerfile
- 9.3/Dockerfile
- 9.4/Dockerfile
- 9.5/Dockerfile
- 9.6/Dockerfile
- Dockerfile-debian.template
See https://salsa.debian.org/postgresql/postgresql-common/blob/997d842ee744687d99a2b2d95c1083a2615c79e8/debian/postgresql-common.postinst#L32-35 for the bit of the upstream Debian package which sets this.
Fixes #478
> Fix Debian "postgres" user HOME (to match Debian package)

- 10/Dockerfile
- 11/Dockerfile
- 9.3/Dockerfile
- 9.4/Dockerfile
- 9.5/Dockerfile
- 9.6/Dockerfile
- Dockerfile-debian.template
(also, remove `*.pyc` files for size -- this makes the non-build image ~311MB and the build image ~312MB when building 11 on amd64)
Closes #484
> Add "stretch-backports" to 11+ for clang-6.0

- 10/alpine/docker-entrypoint.sh
- 10/docker-entrypoint.sh
- 11/alpine/docker-entrypoint.sh
- 11/docker-entrypoint.sh
- 9.3/alpine/docker-entrypoint.sh
- 9.3/docker-entrypoint.sh
- 9.4/alpine/docker-entrypoint.sh
- 9.4/docker-entrypoint.sh
- 9.5/alpine/docker-entrypoint.sh
- 9.5/docker-entrypoint.sh
- 9.6/alpine/docker-entrypoint.sh
- 9.6/docker-entrypoint.sh
- docker-entrypoint.sh
Closes #488
See also:
- https://stackoverflow.com/a/18683163/433558
- https://www.postgresql.org/docs/9.3/static/app-psql.html#APP-PSQL-VARIABLES
- https://www.postgresql.org/docs/9.3/static/app-psql.html#APP-PSQL-INTERPOLATION
> Update psql invocations to properly escape user input!

- 10/alpine/docker-entrypoint.sh
- 10/docker-entrypoint.sh
- 11/alpine/docker-entrypoint.sh
- 11/docker-entrypoint.sh
- 9.3/alpine/docker-entrypoint.sh
- 9.3/docker-entrypoint.sh
- 9.4/alpine/docker-entrypoint.sh
- 9.4/docker-entrypoint.sh
- 9.5/alpine/docker-entrypoint.sh
- 9.5/docker-entrypoint.sh
- 9.6/alpine/docker-entrypoint.sh
- 9.6/docker-entrypoint.sh
- docker-entrypoint.sh
This also closes a slight bug we've had previously where the "postgres" user is _always_ created (now we only create the user specified via the environment variables).
The one catch is that you must specify _both_ `POSTGRES_USER` and `POSTGRES_PASSWORD` if you want to use `--auth-local=md5` (which is honestly kind of expected -- if you want your `local` lines to use `md5` auth, your local users have to have passwords in order to connect locally too).
Closes #280
> Utilize "initdb" functionality better to allow "POSTGRES_INITDB_ARGS=--auth-local=md5"

- 10/Dockerfile
- 11/Dockerfile
- 9.3/Dockerfile
- 9.4/Dockerfile
- 9.5/Dockerfile
- 9.6/Dockerfile
- Dockerfile-debian.template
See https://bugs.debian.org/913614
> Update "gpg" invocations to use "--batch"

- 10/Dockerfile
- 11/Dockerfile
- 9.3/Dockerfile
- 9.4/Dockerfile
- 9.5/Dockerfile
- 9.6/Dockerfile
- Dockerfile-debian.template
This should stop our changes from getting overwritten when folks do weird things like upgrade PostgreSQL inside the image (which isn't a good idea, but this change is still more correct anyhow).
> Use "dpkg-divert" on our sample configuration file (instead of just replacing it)

- 10/Dockerfile
- 10/alpine/Dockerfile
- 11/Dockerfile
- 11/alpine/Dockerfile
- 9.4/Dockerfile
- 9.4/alpine/Dockerfile
- 9.5/Dockerfile
- 9.5/alpine/Dockerfile
- 9.6/Dockerfile
- 9.6/alpine/Dockerfile
- Dockerfile-alpine.template
- Dockerfile-debian.template
Replaces and closes #309 (sorry for the delay :bowing_man:)
> Move end of line comments to their own line to improve readability

- .travis.yml
- 10/alpine/Dockerfile
- 11/alpine/Dockerfile
- 12/Dockerfile
- 12/alpine/Dockerfile
- 12/alpine/docker-entrypoint.sh
- 12/docker-entrypoint.sh
- 9.4/alpine/Dockerfile
- 9.5/alpine/Dockerfile
- 9.6/alpine/Dockerfile
- Dockerfile-alpine.template
- update.sh
> Add 12~beta1

- 10/alpine/docker-entrypoint.sh
- 10/docker-entrypoint.sh
- 11/alpine/docker-entrypoint.sh
- 11/docker-entrypoint.sh
- 12/alpine/docker-entrypoint.sh
- 12/docker-entrypoint.sh
- 9.4/alpine/docker-entrypoint.sh
- 9.4/docker-entrypoint.sh
- 9.5/alpine/docker-entrypoint.sh
- 9.5/docker-entrypoint.sh
- 9.6/alpine/docker-entrypoint.sh
- 9.6/docker-entrypoint.sh
- docker-entrypoint.sh
This will allow a user to write a script to use our script as a base for their own postgres startup.
We need to ensure that that we define the set of functions that users can call. Currently that is any function that doesn't start with an underscore (listed below):
```bash
file_env
docker_create_db_directories
docker_init_database_dir
docker_verify_minimum_env
docker_process_init_files
docker_process_sql
docker_setup_db
docker_setup_env
pg_setup_hba_conf
docker_temp_server_start
docker_temp_server_stop
```
-------------------------------------
EDIT: example updated (and tested) with an example `docker run`.
Here is an example using the current interface to run other init scripts on every start:
```bash
#!/usr/bin/env bash
set -Eeo pipefail
source "$(which docker-entrypoint.sh)" …
```
> Functionalize the entrypoint to allow outside sourcing for extreme customizing of startup

- 10/alpine/docker-entrypoint.sh
- 10/docker-entrypoint.sh
- 11/alpine/docker-entrypoint.sh
- 11/docker-entrypoint.sh
- 12/alpine/docker-entrypoint.sh
- 12/docker-entrypoint.sh
- 9.4/alpine/docker-entrypoint.sh
- 9.4/docker-entrypoint.sh
- 9.5/alpine/docker-entrypoint.sh
- 9.5/docker-entrypoint.sh
- 9.6/alpine/docker-entrypoint.sh
- 9.6/docker-entrypoint.sh
- docker-entrypoint.sh
> Adjust "docker_temp_server_start" to override port for consistent unix socket path

- 11/alpine/Dockerfile
- 12/alpine/Dockerfile
- Dockerfile-alpine.template
- update.sh
> Add JIT support for Alpine on 11+

- 10/alpine/docker-entrypoint.sh
- 10/docker-entrypoint.sh
- 11/alpine/docker-entrypoint.sh
- 11/docker-entrypoint.sh
- 12/alpine/docker-entrypoint.sh
- 12/docker-entrypoint.sh
- 9.4/alpine/docker-entrypoint.sh
- 9.4/docker-entrypoint.sh
- 9.5/alpine/docker-entrypoint.sh
- 9.5/docker-entrypoint.sh
- 9.6/alpine/docker-entrypoint.sh
- 9.6/docker-entrypoint.sh
- docker-entrypoint.sh
This is a follow-up to #642 (closes #644).
> Update temporary server to prefer PGPORT if set (since the client and server both normally respect that variable)

- 10/alpine/docker-entrypoint.sh
- 10/docker-entrypoint.sh
- 11/alpine/docker-entrypoint.sh
- 11/docker-entrypoint.sh
- 12/alpine/docker-entrypoint.sh
- 12/docker-entrypoint.sh
- 9.4/alpine/docker-entrypoint.sh
- 9.4/docker-entrypoint.sh
- 9.5/alpine/docker-entrypoint.sh
- 9.5/docker-entrypoint.sh
- 9.6/alpine/docker-entrypoint.sh
- 9.6/docker-entrypoint.sh
- docker-entrypoint.sh
> Check for "help" to short circuit server starting (since they break when passed to pg_ctl)

- 10/alpine/docker-entrypoint.sh
- 10/docker-entrypoint.sh
- 11/alpine/docker-entrypoint.sh
- 11/docker-entrypoint.sh
- 12/alpine/docker-entrypoint.sh
- 12/docker-entrypoint.sh
- 9.4/alpine/docker-entrypoint.sh
- 9.4/docker-entrypoint.sh
- 9.5/alpine/docker-entrypoint.sh
- 9.5/docker-entrypoint.sh
- 9.6/alpine/docker-entrypoint.sh
- 9.6/docker-entrypoint.sh
- docker-entrypoint.sh
Add `POSTGRES_HOST_AUTH_METHOD` to bring back old behavior and be similar to `MYSQL_ALLOW_EMPTY_PASSWORD`, but add warning when "trust" is used since it disables all passwords
Fixes #580.
> Error when `POSTGRES_PASSWORD` is unset like mysql

- 10/alpine/Dockerfile
- 11/alpine/Dockerfile
- 12/alpine/Dockerfile
- 9.4/alpine/Dockerfile
- 9.5/alpine/Dockerfile
- 9.6/alpine/Dockerfile
- Dockerfile-alpine.template
The adduser command creates the postgres user without specifying a default shell.
alpine-3.11 creates the user with /bin/nologin by default, which differs from the way the user was created when alpine-3.10 was used.
Also, the creation of the postgres user in aports (https://git.alpinelinux.org/aports/tree/main/postgresql/postgresql.pre-install?h=3.11-stable) suggests the usage of /bin/sh.
> Change default shell for user postgres to sh

- 10/alpine/docker-entrypoint.sh
- 10/docker-entrypoint.sh
- 11/alpine/docker-entrypoint.sh
- 11/docker-entrypoint.sh
- 12/alpine/docker-entrypoint.sh
- 12/docker-entrypoint.sh
- 9.5/alpine/docker-entrypoint.sh
- 9.5/docker-entrypoint.sh
- 9.6/alpine/docker-entrypoint.sh
- 9.6/docker-entrypoint.sh
- docker-entrypoint.sh
(Assuming "POSTGRES_HOST_AUTH_METHOD" is not set to the "trust" value which does not require passwords.)
Closes #683
> Clarify that "POSTGRES_PASSWORD" should be non-empty

- 10/Dockerfile
- 10/alpine/docker-entrypoint.sh
- 10/docker-entrypoint.sh
- 11/Dockerfile
- 11/alpine/docker-entrypoint.sh
- 11/docker-entrypoint.sh
- 12/Dockerfile
- 12/alpine/docker-entrypoint.sh
- 12/docker-entrypoint.sh
- 9.5/Dockerfile
- 9.5/alpine/docker-entrypoint.sh
- 9.5/docker-entrypoint.sh
- 9.6/Dockerfile
- 9.6/alpine/docker-entrypoint.sh
- 9.6/docker-entrypoint.sh
- Dockerfile-debian.template
- docker-entrypoint.sh
`xzcat` is provided by `busybox` in Alpine images.
```console
$ docker run -it --rm postgres:alpine bash
bash-5.0# which xzcat
/usr/bin/xzcat
bash-5.0# ls -al /usr/bin/xzcat
lrwxrwxrwx    1 root     root            12 Jan 16 21:52 /usr/bin/xzcat -> /bin/busybox
```
Mirroring addition done in MariaDB: https://github.com/docker-library/mariadb/pull/288 and MySQL: https://github.com/docker-library/mysql/pull/637.
> Add .sql.xz support to docker-entrypoint-initdb.d

- 10/Dockerfile
- 11/Dockerfile
- 12/Dockerfile
- 9.5/Dockerfile
- 9.6/Dockerfile
- Dockerfile-debian.template
The final images somehow contain the following packages which are not necessary:
- libmailutils5* 
- libmariadb3* (postgres:12+)
- mailutils* 
- mariadb-common*  (postgres:12+)
- mysql-common*
- libmariadbclient18*  (postgres:11-)
It also makes sense to "autoremove" at the end to get rid of the packages which are no longer needed. Those packages are (for buster/postgres 12.2): 
- bzip2 
- file 
- guile-2.2-libs 
- libexpat1 
- libfribidi0 
- libgc1c2 
- libgsasl7 
- libidn11
- libkyotocabinet16v5 libltdl7 liblzo2-2 libmagic-mgc libmagic1 libntlm0
- libpython2.7 
- libpython2.7-minimal 
- libpython2.7-stdlib 
- libwrap0
- mailutils-common 
- mime-support
> Remove unnecessary packages from the image

- 10/alpine/docker-entrypoint.sh
- 10/docker-entrypoint.sh
- 11/alpine/docker-entrypoint.sh
- 11/docker-entrypoint.sh
- 12/alpine/docker-entrypoint.sh
- 12/docker-entrypoint.sh
- 9.5/alpine/docker-entrypoint.sh
- 9.5/docker-entrypoint.sh
- 9.6/alpine/docker-entrypoint.sh
- 9.6/docker-entrypoint.sh
- docker-entrypoint.sh
This is a similar change as what was applied in https://github.com/docker-library/mysql/pull/453 (re-applied in https://github.com/docker-library/mysql/pull/643 :sweat_smile:), which would've made the issue in https://github.com/docker-library/postgres/issues/693 much more obvious. :+1: :muscle:
> Fix silently skipped init scripts

- 13/Dockerfile
- 13/alpine/Dockerfile
- 13/alpine/docker-entrypoint.sh
- 13/docker-entrypoint.sh
- Dockerfile-debian.template
- update.sh
> Add PostgreSQL 13 beta 1.

- 10/Dockerfile
- 10/alpine/Dockerfile
- 11/Dockerfile
- 11/alpine/Dockerfile
- 12/Dockerfile
- 12/alpine/Dockerfile
- 13/Dockerfile
- 13/alpine/Dockerfile
- 9.5/Dockerfile
- 9.5/alpine/Dockerfile
- 9.6/Dockerfile
- 9.6/alpine/Dockerfile
- Dockerfile-alpine.template
- Dockerfile-debian.template
Changed the stopsignal to SIGINT, to ensure the database data is always synced to disk, even if clients do not cooperate.
For Details see https://github.com/docker-library/postgres/issues/714
> Changed default stopsignal from SIGTERM to SIGINT

- 10/alpine/Dockerfile
- 11/alpine/Dockerfile
- 12/alpine/Dockerfile
- 13/alpine/Dockerfile
- 9.5/alpine/Dockerfile
- 9.6/alpine/Dockerfile
- Dockerfile-alpine.template
Do not remove static postgres libraries from Alpine based images.
This add near 1.4MB to image size, but allow to complie some extentions
like repmgr without errors
> Keep postgres static libraries in Alpine images

- generate-stackbrew-library.sh
I rewound to commit 09c342c55544feaff8740086bb98c54ad936ac60 to test this and verify that `postgres:13` would go away (and only `postgres:13-rc1` would remain).
- https://github.com/docker-library/postgres/issues/662
- https://github.com/docker-library/postgres/issues/784
> Adjust tagging to enforce explicit pre-release opt-in

- 10/alpine/docker-entrypoint.sh
- 10/docker-entrypoint.sh
- 11/alpine/docker-entrypoint.sh
- 11/docker-entrypoint.sh
- 12/alpine/docker-entrypoint.sh
- 12/docker-entrypoint.sh
- 13/alpine/docker-entrypoint.sh
- 13/docker-entrypoint.sh
- 9.5/alpine/docker-entrypoint.sh
- 9.5/docker-entrypoint.sh
- 9.6/alpine/docker-entrypoint.sh
- 9.6/docker-entrypoint.sh
- docker-entrypoint.sh
> Adjust "chmod" to not fail (since PostgreSQL validates this itself later)

- 10/alpine/docker-entrypoint.sh
- 10/docker-entrypoint.sh
- 11/alpine/docker-entrypoint.sh
- 11/docker-entrypoint.sh
- 12/alpine/docker-entrypoint.sh
- 12/docker-entrypoint.sh
- 13/alpine/docker-entrypoint.sh
- 13/docker-entrypoint.sh
- 9.5/alpine/docker-entrypoint.sh
- 9.5/docker-entrypoint.sh
- 9.6/alpine/docker-entrypoint.sh
- 9.6/docker-entrypoint.sh
- docker-entrypoint.sh
We were already checking for whether `POSTGRES_DB` was set to `postgres`, but this was the underlying motivation for that check (and it turns out that this applies for values of at least `template0` and `template1` as well).
Closes #794
(Just to keep the thread, https://stackoverflow.com/a/18389184/433558 still makes me depressed :sweat_smile: - https://github.com/docker-library/postgres/pull/794#discussion_r535708455)
> Do not try to create databases that already exist

- 10/alpine/docker-entrypoint.sh
- 10/docker-entrypoint.sh
- 11/alpine/docker-entrypoint.sh
- 11/docker-entrypoint.sh
- 12/alpine/docker-entrypoint.sh
- 12/docker-entrypoint.sh
- 13/alpine/docker-entrypoint.sh
- 13/docker-entrypoint.sh
- 9.5/alpine/docker-entrypoint.sh
- 9.5/docker-entrypoint.sh
- 9.6/alpine/docker-entrypoint.sh
- 9.6/docker-entrypoint.sh
- docker-entrypoint.sh
> Explicitly unset PGHOST for temporary server communications

- 14/alpine/Dockerfile
- 14/alpine/docker-entrypoint.sh
- 14/buster/Dockerfile
- 14/buster/docker-entrypoint.sh
- generate-stackbrew-library.sh
- versions.json
Since we swapped to our jq templates, 848 needed to be redone.
Closes #848
```diff
$ diff -u ../official-images/library/postgres <(./generate-stackbrew-library.sh)
--- ../official-images/library/postgres	2021-07-12 14:59:24.487292717 -0700
+++ /dev/fd/63	2021-07-12 14:59:29.359304547 -0700
@@ -1,9 +1,19 @@
-# this file is generated via https://github.com/docker-library/postgres/blob/0d2e407c7c9baf10e05a01811d9938f45c8cb40e/generate-stackbrew-library.sh
+# this file is generated via https://github.com/docker-library/postgres/blob/b1f3f0a43039c3691cf0c762675488dc7ddac8b5/generate-stackbrew-library.sh
Maintainers: Tianon Gravi <admwiggin@gmail.com> (@tianon),
Joseph Ferguson <yosifkit@gmail.com> (@yosifkit)
GitRepo: https://github.com/docker-library/postgres.git
+Tags: 14beta2, …
```
> Add 14-beta2

- 10/alpine/Dockerfile
- 11/alpine/Dockerfile
- 12/alpine/Dockerfile
- 13/alpine/Dockerfile
- 14/alpine/Dockerfile
- 9.6/alpine/Dockerfile
- Dockerfile-alpine.template
The readme on dockerhub says:
> When using the Alpine variants, any postgres extension not listed in postgres-contrib will need to be compiled in your own image (again, see github.com/postgis/docker-postgis for a concrete example).
However, not all extensions in contrib are available. The language extension `plperl`, `plpython` and `pltcl`, as well as related contrib modules (e.g. `hstore_*`, `jsonb_*`, ...) are missing.
Only in very rare cases, when the postgres version matches the one distributed in the current alpine distribution, one can install e.g. `plpython` via `apk add postgresql-plpython3` (with a bit of moving files around to their proper location). However, this is not sustainable: It currently works for pg 13.x on alpine 3.14, but not for pg 14.x anymore.
Compiling those …
> Add missing contrib modules / pl extensions to alpine image

- 10/bullseye/Dockerfile
- 10/stretch/Dockerfile
- 11/bullseye/Dockerfile
- 11/stretch/Dockerfile
- 12/bullseye/Dockerfile
- 13/bullseye/Dockerfile
- 14/bullseye/Dockerfile
- 9.6/bullseye/Dockerfile
- 9.6/stretch/Dockerfile
- Dockerfile-debian.template
Signed-off-by: daniel sutton <daniel@ducksecops.uk>
Upgradet GOSU 1.14 from prevous GOSU 1.12. Newer version is based on GO 1.16.7 which is supported.
> update GOSU to 1.14

- 10/bullseye/Dockerfile
- 10/stretch/Dockerfile
- 11/bullseye/Dockerfile
- 11/stretch/Dockerfile
- 12/bullseye/Dockerfile
- 13/bullseye/Dockerfile
- 14/bullseye/Dockerfile
- 9.6/bullseye/Dockerfile
- 9.6/stretch/Dockerfile
- Dockerfile-debian.template
> A sources.list entry SHOULD have the signed-by option set.
>
> \- https://wiki.debian.org/DebianRepository/UseThirdParty#Sources.list_entry
While `signed-by` is not required, this makes the Dockerfile a slightly better example of installing something from a third-party repo. This also updates the key to be in "ASCII-armored" format.
> Narrow postgres apt key package scope

- 10/alpine/Dockerfile
- 10/alpine/docker-entrypoint.sh
- 10/bullseye/Dockerfile
- 10/bullseye/docker-entrypoint.sh
- 10/stretch/Dockerfile
- 10/stretch/docker-entrypoint.sh
- 11/alpine/Dockerfile
- 11/alpine/docker-entrypoint.sh
- 11/bullseye/Dockerfile
- 11/bullseye/docker-entrypoint.sh
- 11/stretch/Dockerfile
- 11/stretch/docker-entrypoint.sh
- 12/alpine/Dockerfile
- 12/alpine/docker-entrypoint.sh
- 12/bullseye/Dockerfile
- 12/bullseye/docker-entrypoint.sh
- 13/alpine/Dockerfile
- 13/alpine/docker-entrypoint.sh
- 13/bullseye/Dockerfile
- 13/bullseye/docker-entrypoint.sh
- 14/alpine/Dockerfile
- 14/alpine/docker-entrypoint.sh
- 14/bullseye/Dockerfile
- 14/bullseye/docker-entrypoint.sh
- Dockerfile-alpine.template
- Dockerfile-debian.template
- docker-entrypoint.sh
Zstandard outperforms gzip and xz in many metrics, it would be beneficial to support it.
Mirroring additions done in MariaDB (MariaDB/mariadb-docker#376) and MySQL (docker-library/mysql#773).
> Add .sql.zst support to docker-entrypoint-initdb.d

- 10/alpine/Dockerfile
- 11/alpine/Dockerfile
- 12/alpine/Dockerfile
- 13/alpine/Dockerfile
- 14/alpine/Dockerfile
- Dockerfile-alpine.template
In e8ebf74e50128123a8d0220b85e357ef2d73a7ec zstd was installed as build dependency and thus does not end up in the final image which in turn renders docker-entrypoint.sh broken when using *.sql.zst files.
> Fix new zstd support for alpine images

- 10/alpine/docker-entrypoint.sh
- 10/bullseye/docker-entrypoint.sh
- 10/stretch/docker-entrypoint.sh
- 11/alpine/docker-entrypoint.sh
- 11/bullseye/docker-entrypoint.sh
- 11/stretch/docker-entrypoint.sh
- 12/alpine/docker-entrypoint.sh
- 12/bullseye/docker-entrypoint.sh
- 13/alpine/docker-entrypoint.sh
- 13/bullseye/docker-entrypoint.sh
- 14/alpine/docker-entrypoint.sh
- 14/bullseye/docker-entrypoint.sh
- 15/alpine/docker-entrypoint.sh
- 15/bullseye/docker-entrypoint.sh
- docker-entrypoint.sh
I think POSTGRES_INITDB_WALDIR is the only case an undefined variable is used. Fixed.
> set -u for docker-entrypoint.sh

- 15/alpine/Dockerfile
- Dockerfile-alpine.template
pg >=15 alpine: **"Add configure option --with-zstd to enable Zstandard builds"**
* https://www.postgresql.org/docs/15/release-15.html 
NOW: Test `postgres:15beta1-alpine` ( current )
```
docker run --name current_pgalpine15 -e POSTGRES_PASSWORD=pi31415926 -d postgres:15beta1-alpine -c wal_compression=zstd
2022-06-30 06:48:41.233 GMT [31] FATAL:  invalid value for parameter "wal_compression": "zstd"
2022-06-30 06:48:41.233 GMT [31] HINT:  Available values: pglz, lz4, on, off.
```
PROPOSAL: Test pgalpine15_zstd 
```bash
$ cd ./15/alpine
$ docker build -t pgalpine15_zstd .
$ docker run --name pgalpine15_zstd -e POSTGRES_PASSWORD=pi31415926 -d pgalpine15_zstd -c wal_compression=zstd
$ docker exec -ti pgalpine15_zstd psql -U postgres -c "SHOW wal_compression;"
wal_compression …
```
> pg >=15 alpine: Enable Zstandard builds "--with-zstd"

- 11/alpine/docker-entrypoint.sh
- 11/bullseye/docker-entrypoint.sh
- 12/alpine/docker-entrypoint.sh
- 12/bullseye/docker-entrypoint.sh
- 13/alpine/docker-entrypoint.sh
- 13/bullseye/docker-entrypoint.sh
- 14/alpine/docker-entrypoint.sh
- 14/bullseye/docker-entrypoint.sh
- 15/alpine/docker-entrypoint.sh
- 15/bullseye/docker-entrypoint.sh
- docker-entrypoint.sh
The use of the `echo` shell built-in has been actively discouraged for a long time, but it's really convenient so we keep doing it.  This converts them all to use `printf` appropriately such that we avoid issues like `echo "$someVar"` from doing the wrong thing if `$someVar` is `-n` or similar.
Closes #1023
> Convert all entrypoint "echo"s to "printf"

- 11/alpine/docker-entrypoint.sh
- 11/bullseye/docker-entrypoint.sh
- 12/alpine/docker-entrypoint.sh
- 12/bullseye/docker-entrypoint.sh
- 13/alpine/docker-entrypoint.sh
- 13/bullseye/docker-entrypoint.sh
- 14/alpine/docker-entrypoint.sh
- 14/bullseye/docker-entrypoint.sh
- 15/alpine/docker-entrypoint.sh
- 15/bullseye/docker-entrypoint.sh
- docker-entrypoint.sh
https://github.com/docker-library/postgres/issues/1024 converted all `echo` calls to `printf`, but this change causes the password file used by `initdb` to be blank rather than contain a single newline. As a result, `initdb` will fail to start with an empty value with the error:
```
initdb: error: password file "/dev/fd/63" is empty
```
`POSTGRES_PASSWORD` can be blank if `POSTGRES_HOST_AUTH_METHOD=trust` is used. This change adds a newline to restore the original behavior.
Closes #1025
> Add newline to `POSTGRES_PASSWORD` file for initdb

- 11/alpine/Dockerfile
- 12/alpine/Dockerfile
- 13/alpine/Dockerfile
- 14/alpine/Dockerfile
- 15/alpine/Dockerfile
- Dockerfile-alpine.template
This will fix the current failing builds on ppc64le:
```console
+ apk add --no-cache --virtual .postgresql-rundeps so:libLLVM-15.so so:libc.musl-ppc64le.so.1 so:libcrypto.so.3 so:libedit.so.0 so:libgcc_s.so.1 so:libgssapi_krb5.so.2 so:libicui18n.so.72 so:libicuuc.so.72 so:libldap.so.2 so:libssl.so.3 so:libstdc++.so.6 so:libuuid.so.1 so:libxml2.so.2 so:libxslt.so.1 so:libz.so.1 bash nss_wrapper su-exec tzdata zstd icu-data-full
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/ppc64le/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/ppc64le/APKINDEX.tar.gz
ERROR: unable to select packages:
.postgresql-rundeps-20221222.204533:
masked in: cache
satisfies: world[.postgresql-rundeps=20221222.204533]
nss_wrapper (no such package):
required by: …
```
> Skip unavailable nss_wrapper on ppc64le

- 11/alpine/Dockerfile
- 11/alpine/docker-entrypoint.sh
- 11/bullseye/docker-entrypoint.sh
- 12/alpine/Dockerfile
- 12/alpine/docker-entrypoint.sh
- 12/bullseye/docker-entrypoint.sh
- 13/alpine/Dockerfile
- 13/alpine/docker-entrypoint.sh
- 13/bullseye/docker-entrypoint.sh
- 14/alpine/Dockerfile
- 14/alpine/docker-entrypoint.sh
- 14/bullseye/docker-entrypoint.sh
- 15/alpine/Dockerfile
- 15/alpine/docker-entrypoint.sh
- 15/bullseye/docker-entrypoint.sh
- Dockerfile-alpine.template
- docker-entrypoint.sh
This still supports the "arbitrary user" use case but with slightly tighter permissions on the end result.
This one is a little bit more "special" other images (due to the existing runtime/entrypoint modification of the directory modes) so I've tried to pick reasonable values for both halves.
> Update permissions from 777 to 1777

- 11/bullseye/Dockerfile
- 12/bullseye/Dockerfile
- 13/bullseye/Dockerfile
- 14/bullseye/Dockerfile
- 15/bullseye/Dockerfile
- Dockerfile-debian.template
This is pulled in automatically via `gnupg`, and moved from `Recommends` to `Depends` in https://salsa.debian.org/debian/gnupg2/-/commit/99474ad900a8bcdd0e7b68f986fec0013fc01470, which has been part of `src:gnupg2` since 2.1.21-4 (and every supported version of both Debian _and_ Ubuntu have 2.2.x 😇).
> Remove explicit `dirmngr` reference

- 11/alpine/Dockerfile
- 12/alpine/Dockerfile
- 13/alpine/Dockerfile
- 14/alpine/Dockerfile
- 15/alpine/Dockerfile
- Dockerfile-alpine.template
- Dockerfile-debian.template
PostgreSQL doesn't support llvm 16 (https://github.com/docker-library/postgres/issues/1076#issuecomment-1545209600):
- https://www.postgresql.org/message-id/flat/17927-2d7146227560bdf3%40postgresql.org
- https://www.postgresql.org/message-id/flat/17929-71c7a59e1930980b%40postgresql.org
Thank you for your comments on #1076 pointing me in a direction for a fix ❤️. Apologies for any stress and work that this caused 🙇‍♂️. With the added test in https://github.com/docker-library/official-images/pull/14646, we shouldn't run into this issue again.
Fixes https://github.com/docker-library/postgres/issues/1076
> Downgrade llvm to 15 to fix jit support

- 11/alpine/Dockerfile
- 12/alpine/Dockerfile
- 13/alpine/Dockerfile
- 14/alpine/Dockerfile
- 15/alpine/Dockerfile
- Dockerfile-alpine.template
Also, remove deprecated/removed `--with-krb5` (deprecated in 8.3, removed in 9.4; https://github.com/postgres/postgres/commit/98de86e4221a418d670db86bf28ff15e880beadc).
Closes #1078
> Add `--enable-option-checking=fatal` to `configure` flags

- generate-stackbrew-library.sh
> September 14, 2023 - The PostgreSQL Global Development Group today announced the release of PostgreSQL 16
>
>\- https://www.postgresql.org/about/news/postgresql-16-released-2715/
```diff
$ diff -u ../official-images/library/postgres <(./generate-stackbrew-library.sh)
--- ../official-images/library/postgres 2023-09-01 13:26:17.532182117 -0700
+++ /dev/fd/63  2023-09-14 14:35:27.532811966 -0700
@@ -1,45 +1,45 @@
-# this file is generated via https://github.com/docker-library/postgres/blob/5ea98fe00be95fbbe642732d62af3b4dbc83f442/generate-stackbrew-library.sh
+# this file is generated via https://github.com/docker-library/postgres/blob/7df6bc166fbf0d7f28c85700235012317a22f88e/generate-stackbrew-library.sh
Maintainers: Tianon Gravi <admwiggin@gmail.com> (@tianon),
Joseph Ferguson …
```
> Move latest to 16

- 11/alpine3.17/Dockerfile
- 11/alpine3.18/Dockerfile
- 11/bookworm/Dockerfile
- 11/bullseye/Dockerfile
- 12/alpine3.17/Dockerfile
- 12/alpine3.18/Dockerfile
- 12/bookworm/Dockerfile
- 12/bullseye/Dockerfile
- 13/alpine3.17/Dockerfile
- 13/alpine3.18/Dockerfile
- 13/bookworm/Dockerfile
- 13/bullseye/Dockerfile
- 14/alpine3.17/Dockerfile
- 14/alpine3.18/Dockerfile
- 14/bookworm/Dockerfile
- 14/bullseye/Dockerfile
- 15/alpine3.17/Dockerfile
- 15/alpine3.18/Dockerfile
- 15/bookworm/Dockerfile
- 15/bullseye/Dockerfile
- 16/alpine3.17/Dockerfile
- 16/alpine3.18/Dockerfile
- 16/bookworm/Dockerfile
- 16/bullseye/Dockerfile
- Dockerfile-alpine.template
- Dockerfile-debian.template
I somehow missed Debian in 25b3034e9b0155c3e71acaf650243e7d12a571c1 / https://github.com/docker-library/postgres/pull/1058 (only updated Alpine), so this updates Debian in the same way.
> This still supports the "arbitrary user" use case but with slightly tighter permissions on the end result.
>
> This one is a little bit more "special" other images (due to the existing runtime/entrypoint modification of the directory modes) so I've tried to pick reasonable values for both halves.
> Update permissions from 777 to 1777 (redux)

- 11/bookworm/Dockerfile
- 11/bullseye/Dockerfile
- 12/bookworm/Dockerfile
- 12/bullseye/Dockerfile
- 13/bookworm/Dockerfile
- 13/bullseye/Dockerfile
- 14/bookworm/Dockerfile
- 14/bullseye/Dockerfile
- 15/bookworm/Dockerfile
- 15/bullseye/Dockerfile
- 16/bookworm/Dockerfile
- 16/bullseye/Dockerfile
- Dockerfile-debian.template
The use of manually calling localdef caused any future update to the locales package to remove the manually installed locales, since locale-gen takes precendence. This would usually be encountered when a downstream Dockerfile added additional packages, and as a side effect caused an upgrade to the locales package.
Fix by relying on the /etc/locale.gen file, which is the official place to specify which locales should be installed.
Fixes #1112
> Debian images: Use locale-gen instead of localdef

- .gitignore
- 12/alpine3.18/Dockerfile
- 12/alpine3.19/Dockerfile
- 13/alpine3.18/Dockerfile
- 13/alpine3.19/Dockerfile
- 14/alpine3.18/Dockerfile
- 14/alpine3.19/Dockerfile
- 15/alpine3.18/Dockerfile
- 15/alpine3.19/Dockerfile
- 16/alpine3.18/Dockerfile
- 16/alpine3.19/Dockerfile
- Dockerfile-alpine.template
- apply-templates.sh
This reverts commit 6f4ae836406b010948f01fbcb400a31dca4fdf52.
This is now supported by the Syft Scanner
> Revert "Added inline SBOM for binaries downloaded outside package manager

- 12/alpine3.18/docker-entrypoint.sh
- 12/alpine3.19/docker-entrypoint.sh
- 12/bookworm/docker-entrypoint.sh
- 12/bullseye/docker-entrypoint.sh
- 13/alpine3.18/docker-entrypoint.sh
- 13/alpine3.19/docker-entrypoint.sh
- 13/bookworm/docker-entrypoint.sh
- 13/bullseye/docker-entrypoint.sh
- 14/alpine3.18/docker-entrypoint.sh
- 14/alpine3.19/docker-entrypoint.sh
- 14/bookworm/docker-entrypoint.sh
- 14/bullseye/docker-entrypoint.sh
- 15/alpine3.18/docker-entrypoint.sh
- 15/alpine3.19/docker-entrypoint.sh
- 15/bookworm/docker-entrypoint.sh
- 15/bullseye/docker-entrypoint.sh
- 16/alpine3.18/docker-entrypoint.sh
- 16/alpine3.19/docker-entrypoint.sh
- 16/bookworm/docker-entrypoint.sh
- 16/bullseye/docker-entrypoint.sh
- docker-entrypoint.sh
In 14+, the arbitrary length limitations have been removed from the PostgreSQL server (https://github.com/postgres/postgres/commit/67a472d71c98c3d2fa322a1b4013080b20720b98).
Updates #511
See https://github.com/docker-library/postgres/issues/507#issuecomment-1848667847
> Only print password length warning for 12 and 13

- 12/bookworm/Dockerfile
- 12/bullseye/Dockerfile
- 13/bookworm/Dockerfile
- 13/bullseye/Dockerfile
- 14/bookworm/Dockerfile
- 14/bullseye/Dockerfile
- 15/bookworm/Dockerfile
- 15/bullseye/Dockerfile
- 16/bookworm/Dockerfile
- 16/bullseye/Dockerfile
- Dockerfile-debian.template
https://www.postgresql.org/docs/16/app-psql.html#APP-PSQL-META-COMMAND-PSET-PAGER https://github.com/postgres/postgres/blob/REL_16_1/src/include/fe_utils/print.h#L25
(if "less" is available, it gets used as the default pager for psql, and it only adds ~1.5MiB to our image size)
Closes #1115
> Add `less` to Debian variants

- .github/workflows/ci.yml
- .github/workflows/verify-templating.yml
Prevents a Node.js 16 deprecation warning
https://github.com/docker-library/postgres/actions/runs/9198118729
> Bump `actions/checkout` to v4

- 12/alpine3.19/Dockerfile
- 12/alpine3.20/Dockerfile
- 13/alpine3.19/Dockerfile
- 13/alpine3.20/Dockerfile
- 14/alpine3.19/Dockerfile
- 14/alpine3.20/Dockerfile
- 15/alpine3.19/Dockerfile
- 15/alpine3.20/Dockerfile
- 16/alpine3.19/Dockerfile
- 16/alpine3.20/Dockerfile
- 17/alpine3.19/Dockerfile
- 17/alpine3.19/docker-ensure-initdb.sh
- 17/alpine3.19/docker-entrypoint.sh
- 17/alpine3.20/Dockerfile
- 17/alpine3.20/docker-ensure-initdb.sh
- 17/alpine3.20/docker-entrypoint.sh
- 17/bookworm/Dockerfile
- 17/bookworm/docker-ensure-initdb.sh
- 17/bookworm/docker-entrypoint.sh
- 17/bullseye/Dockerfile
- 17/bullseye/docker-ensure-initdb.sh
- 17/bullseye/docker-entrypoint.sh
- Dockerfile-alpine.template
- versions.json
> Add 17 beta1

- 12/alpine3.19/Dockerfile
- 12/alpine3.20/Dockerfile
- 12/bookworm/Dockerfile
- 12/bullseye/Dockerfile
- 13/alpine3.19/Dockerfile
- 13/alpine3.20/Dockerfile
- 13/bookworm/Dockerfile
- 13/bullseye/Dockerfile
- 14/alpine3.19/Dockerfile
- 14/alpine3.20/Dockerfile
- 14/bookworm/Dockerfile
- 14/bullseye/Dockerfile
- 15/alpine3.19/Dockerfile
- 15/alpine3.20/Dockerfile
- 15/bookworm/Dockerfile
- 15/bullseye/Dockerfile
- 16/alpine3.19/Dockerfile
- 16/alpine3.20/Dockerfile
- 16/bookworm/Dockerfile
- 16/bullseye/Dockerfile
- 17/alpine3.19/Dockerfile
- 17/alpine3.20/Dockerfile
- 17/bookworm/Dockerfile
- 17/bullseye/Dockerfile
- Dockerfile-alpine.template
- Dockerfile-debian.template
Instead of chaining three commands together, we can use a single command that's purpose-built for exactly the thing we're trying to do (pre-create directories with appropriate ownership and permissions).
> Use `install` instead of `mkdir && chown && chmod`

- Dockerfile-alpine.template
The end result is the same, but the construction is more ergonomic.
See also https://github.com/docker-library/buildpack-deps/pull/165 (and linked)
> Use jq's `IN()` instead of `index()`

- 12/alpine3.20/Dockerfile
- 12/alpine3.21/Dockerfile
- 13/alpine3.20/Dockerfile
- 13/alpine3.21/Dockerfile
- 14/alpine3.20/Dockerfile
- 14/alpine3.21/Dockerfile
- 15/alpine3.20/Dockerfile
- 15/alpine3.21/Dockerfile
- 16/alpine3.20/Dockerfile
- 16/alpine3.21/Dockerfile
- 17/alpine3.20/Dockerfile
- 17/alpine3.21/Dockerfile
- Dockerfile-alpine.template
Fixes #1296
~Also drops Alpine 3.19~ Now just the llvm bump part
This should be purely additive to https://github.com/docker-library/postgres/pull/1298, so we can merge that first once the Alpine images are available for testing.
> In Alpine 3.21 bump llvm version

- 13/alpine3.20/docker-entrypoint.sh
- 13/alpine3.21/docker-entrypoint.sh
- 13/bookworm/docker-entrypoint.sh
- 13/bullseye/docker-entrypoint.sh
- 14/alpine3.20/docker-entrypoint.sh
- 14/alpine3.21/docker-entrypoint.sh
- 14/bookworm/docker-entrypoint.sh
- 14/bullseye/docker-entrypoint.sh
- 15/alpine3.20/docker-entrypoint.sh
- 15/alpine3.21/docker-entrypoint.sh
- 15/bookworm/docker-entrypoint.sh
- 15/bullseye/docker-entrypoint.sh
- 16/alpine3.20/docker-entrypoint.sh
- 16/alpine3.21/docker-entrypoint.sh
- 16/bookworm/docker-entrypoint.sh
- 16/bullseye/docker-entrypoint.sh
- 17/alpine3.20/docker-entrypoint.sh
- 17/alpine3.21/docker-entrypoint.sh
- 17/bookworm/docker-entrypoint.sh
- 17/bullseye/docker-entrypoint.sh
- docker-entrypoint.sh
Some container runtimes, such as podman, can expose a notify socket when used in combination with systemd. The socket's path is available in the `NOTIFY_SOCKET` envirionment variable.
Postgres has native support for this notification socket, and will write a `READY=1` message once it is ready and accepting connections. Unfortunately, the temporary server used by the `docker-entrypoint.sh` to populate the database also sends a message on the socket, making it appear as though the container is ready and serving connections when it is not.
To avoid this issue we need to unset the NOTIFY_SOCKET envirionment variable before starting the temporary server. The real server will eventually find the socket and send the appropriate message.
The easiest way to test this is through the systemd-run …
> Unset NOTIFY_SOCKET when running the temporary server.

- 13/bookworm/Dockerfile
- 13/bullseye/Dockerfile
- 14/bookworm/Dockerfile
- 14/bullseye/Dockerfile
- 15/bookworm/Dockerfile
- 15/bullseye/Dockerfile
- 16/bookworm/Dockerfile
- 16/bullseye/Dockerfile
- 17/bookworm/Dockerfile
- 17/bullseye/Dockerfile
- Dockerfile-debian.template
>B-D on postgresql-common-dev.
>\- https://salsa.debian.org/postgresql/postgresql/-/commit/f4338a0d28cf4541956bddb0f4e444ba9dba81b9
This should fix our failing builds on arches that build the apt packages.
> ```
> E: Unable to find a source package for pgdg-keyring
> ```
2022-11-11: Repository key handling changed: https://www.postgresql.org/message-id/Y25%2BRkZxiZKBOKio%40msg.df7cb.de
> In postgresql-common 246, this has been changed such that
> postgresql-common itself contains the key files, and the trusted.gpg.d
> symlink is created when a /etc/apt/sources.list.d/pgdg.list is found.
2025-02-20: https://www.postgresql.org/message-id/E1tl6i4-00AYNF-P6@atalia.postgresql.org
>   * Move pgdg-keyring conflicts to postgresql-client-common where the files
>    are located now.
> Update apt build depend

- 18/bookworm/Dockerfile
- 18/bullseye/Dockerfile
- Dockerfile-debian.template
See:
- https://salsa.debian.org/postgresql/postgresql/-/commit/eaa9529d8ecb0beaeebeb5b09362dbdf4ce34c0c  
"Make LLVM architectures a inclusion list so it works in the Architecture field."  
(which removes i386, notably)
- https://salsa.debian.org/postgresql/postgresql/-/commit/1d6f624592d18d0cb0d694675037984f0d44b5ae
"Disable JIT on loong64 and riscv64 again, still segfaulting."
> Only install 18+ JIT package on architectures where it's supported

- 13/bookworm/Dockerfile
- 13/trixie/Dockerfile
- 14/bookworm/Dockerfile
- 14/trixie/Dockerfile
- 15/bookworm/Dockerfile
- 15/trixie/Dockerfile
- 16/bookworm/Dockerfile
- 16/trixie/Dockerfile
- 17/bookworm/Dockerfile
- 17/trixie/Dockerfile
- 18/bookworm/Dockerfile
- 18/trixie/Dockerfile
- Dockerfile-debian.template
The PostgreSQL documentation for packages
(https://www.postgresql.org/download/linux/ubuntu/) does not have a trailing slash.
> debian: align postgres repo url with docs

- 13/alpine3.21/Dockerfile
- 13/alpine3.22/Dockerfile
- 14/alpine3.21/Dockerfile
- 14/alpine3.22/Dockerfile
- 15/alpine3.21/Dockerfile
- 15/alpine3.22/Dockerfile
- 16/alpine3.21/Dockerfile
- 16/alpine3.22/Dockerfile
- 17/alpine3.21/Dockerfile
- 17/alpine3.22/Dockerfile
- 18/alpine3.21/Dockerfile
- 18/alpine3.22/Dockerfile
- Dockerfile-alpine.template
This is a bit complicated to use in Docker (because `io_uring` has a long and storied security story), but it is a new feature of 18+ that we should probably explicitly support for users who want to jump through the hoops to use it despite the security risk.
Additionally, this re-alphabetizes our `--with-xxx` flags.
- See also https://github.com/docker-library/postgres/issues/1365  
(with special thanks to @ImreSamu for being so excellent all the time)
> Add liburing support to 18+
