docker-library/postgres

8.4/docker-entrypoint.sh, 9.0/docker-entrypoint.sh, 9.1/docker-entrypoint.sh, 9.2/docker-entrypoint.sh, 9.3/docker-entrypoint.sh, 9.4/docker-entrypoint.sh, docker-entrypoint.sh
See discussion in #51.
Fixes #50
=> Ensure /run/postgresql has correct ownership and permissions

9.5/Dockerfile, 9.5/docker-entrypoint.sh
http://www.postgresql.org/about/news/1595/ :tada:
=> Add 9.5-alpha1

9.0/Dockerfile, 9.1/Dockerfile, 9.2/Dockerfile, 9.3/Dockerfile, 9.4/Dockerfile, 9.5/Dockerfile, Dockerfile.template, update.sh
=> Switch from "wheezy" over to "jessie"

9.0/docker-entrypoint.sh, 9.1/docker-entrypoint.sh, 9.2/docker-entrypoint.sh, 9.3/docker-entrypoint.sh, 9.4/docker-entrypoint.sh, 9.5/docker-entrypoint.sh, docker-entrypoint.sh
=> Stops docker-entrypoint.sh on psql error

9.1/Dockerfile, 9.2/Dockerfile, 9.3/Dockerfile, 9.4/Dockerfile, 9.5/Dockerfile, Dockerfile.template
See also docker-library/official-images#1420.
=> Fix "gpg" usage to stop relying on deprecated and insecure behavior

9.1/docker-entrypoint.sh, 9.2/docker-entrypoint.sh, 9.3/docker-entrypoint.sh, 9.4/docker-entrypoint.sh, 9.5/docker-entrypoint.sh, docker-entrypoint.sh
See also https://github.com/docker-library/mysql/pull/126
=> Refactor entrypoint to allow "sql.gz" files as well

9.1/docker-entrypoint.sh, 9.2/docker-entrypoint.sh, 9.3/docker-entrypoint.sh, 9.4/docker-entrypoint.sh, 9.5/docker-entrypoint.sh, 9.6/docker-entrypoint.sh, docker-entrypoint.sh
=> Use gosu postgres when writing to hba.cnf so that drop-cap dac_override works

9.2/alpine/docker-entrypoint.sh, 9.2/docker-entrypoint.sh, 9.3/alpine/docker-entrypoint.sh, 9.3/docker-entrypoint.sh, 9.4/alpine/docker-entrypoint.sh, 9.4/docker-entrypoint.sh, 9.5/alpine/docker-entrypoint.sh, 9.5/docker-entrypoint.sh, 9.6/alpine/docker-entrypoint.sh, 9.6/docker-entrypoint.sh, docker-entrypoint.sh
Sorry, but not all developers know this extra bash syntax.
But please keep it simple for other developers.
If readability is not so important for you just close this pull.
Thanks
=> Simplify `docker-entrypoint.sh` append one line to EOF

9.2/alpine/Dockerfile, 9.3/alpine/Dockerfile, 9.4/alpine/Dockerfile, 9.5/alpine/Dockerfile, 9.6/alpine/Dockerfile, Dockerfile-alpine.template
=> Add "mkdir ~postgres" with proper permissions

10/Dockerfile, 10/alpine/Dockerfile, 9.3/Dockerfile, 9.3/alpine/Dockerfile, 9.4/Dockerfile, 9.4/alpine/Dockerfile, 9.5/Dockerfile, 9.5/alpine/Dockerfile, 9.6/Dockerfile, 9.6/alpine/Dockerfile, Dockerfile-alpine.template, Dockerfile-debian.template
=> Fix PATH, especially for cyrillic characters in psql

10/Dockerfile, 9.3/Dockerfile, 9.4/Dockerfile, 9.5/Dockerfile, 9.6/Dockerfile, Dockerfile-debian.template
See https://github.com/docker-library/python/issues/236 for details.
=> Swap from "gnupg2" to "gnupg"

10/alpine/docker-entrypoint.sh, 10/docker-entrypoint.sh, 11/alpine/docker-entrypoint.sh, 11/docker-entrypoint.sh, 9.4/alpine/docker-entrypoint.sh, 9.4/docker-entrypoint.sh, 9.5/alpine/docker-entrypoint.sh, 9.5/docker-entrypoint.sh, 9.6/alpine/docker-entrypoint.sh, 9.6/docker-entrypoint.sh, docker-entrypoint.sh
=> Warn on POSTGRES_PASSWORD of 100+ characters

10/alpine/Dockerfile, 11/alpine/Dockerfile, 12/alpine/Dockerfile, 13/alpine/Dockerfile, 9.5/alpine/Dockerfile, 9.6/alpine/Dockerfile, Dockerfile-alpine.template
=> Remove (no longer necessary) Alpine fetch-deps

10/alpine/Dockerfile, 11/alpine/Dockerfile, 12/alpine/Dockerfile, 13/alpine/Dockerfile, 9.5/alpine/Dockerfile, 9.6/alpine/Dockerfile, update.sh
=> Update to Alpine 3.13

10/alpine/docker-entrypoint.sh, 10/bullseye/docker-entrypoint.sh, 10/stretch/docker-entrypoint.sh, 11/alpine/docker-entrypoint.sh, 11/bullseye/docker-entrypoint.sh, 11/stretch/docker-entrypoint.sh, 12/alpine/docker-entrypoint.sh, 12/bullseye/docker-entrypoint.sh, 13/alpine/docker-entrypoint.sh, 13/bullseye/docker-entrypoint.sh, 14/alpine/docker-entrypoint.sh, 14/bullseye/docker-entrypoint.sh, 9.6/alpine/docker-entrypoint.sh, 9.6/bullseye/docker-entrypoint.sh, 9.6/stretch/docker-entrypoint.sh, docker-entrypoint.sh
See https://salsa.debian.org/sssd-team/nss-wrapper/-/commit/b9925a653a54e24d09d9b498a2d913729f7abb15 for the breaking change which necessitates this.
=> Fix "libnss-wrapper" usage on bullseye

10/alpine/docker-entrypoint.sh, 10/bullseye/docker-entrypoint.sh, 10/stretch/docker-entrypoint.sh, 11/alpine/docker-entrypoint.sh, 11/bullseye/docker-entrypoint.sh, 11/stretch/docker-entrypoint.sh, 12/alpine/docker-entrypoint.sh, 12/bullseye/docker-entrypoint.sh, 13/alpine/docker-entrypoint.sh, 13/bullseye/docker-entrypoint.sh, 14/alpine/docker-entrypoint.sh, 14/bullseye/docker-entrypoint.sh, 9.6/alpine/docker-entrypoint.sh, 9.6/bullseye/docker-entrypoint.sh, 9.6/stretch/docker-entrypoint.sh, docker-entrypoint.sh
original code didn't respect libnss-wrapper at other locations
fixes #918
=> fix unset/cleanup "nss_wrapper" bits

10/bullseye/Dockerfile, 10/stretch/Dockerfile, 11/bullseye/Dockerfile, 11/stretch/Dockerfile, 12/bullseye/Dockerfile, 13/bullseye/Dockerfile, 14/bullseye/Dockerfile, 9.6/bullseye/Dockerfile, 9.6/stretch/Dockerfile, Dockerfile-debian.template
See https://salsa.debian.org/postgresql/postgresql/-/commit/99f44476e258cae6bf9e919219fa2c5414fa2876
=> Fix deb-build with newer packages that Build-Depends: postgresql-common

15/alpine/Dockerfile, 15/alpine/docker-entrypoint.sh, 15/bullseye/Dockerfile, 15/bullseye/docker-entrypoint.sh, versions.json
=> Add 15 pre-release

10/alpine/Dockerfile, 11/alpine/Dockerfile, 12/alpine/Dockerfile, 13/alpine/Dockerfile, 14/alpine/Dockerfile, 15/alpine/Dockerfile, Dockerfile-alpine.template
See https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.16.0#ICU_data_split
Fixes #965
=> Add "icu-data-full" to all Alpine images

11/alpine/Dockerfile, 12/alpine/Dockerfile, 13/alpine/Dockerfile, 14/alpine/Dockerfile, 15/alpine/Dockerfile, versions.json, versions.sh
Alpine 3.17 was released a week ago: https://www.alpinelinux.org/posts/Alpine-3.17.0-released.html
Would be great to update.
=> Update to alpine 3.17

11/alpine/Dockerfile, 12/alpine/Dockerfile, 13/alpine/Dockerfile, 14/alpine/Dockerfile, 15/alpine/Dockerfile, Dockerfile-alpine.template
Same as #999, but nss_wrapper is now in the stable release.
=> Add nss_wrapper to alpine

11/bullseye/Dockerfile, 12/bullseye/Dockerfile, 13/bullseye/Dockerfile, 14/bullseye/Dockerfile, 15/bullseye/Dockerfile, Dockerfile-debian.template
See https://github.com/tianon/gosu/releases/tag/1.16 (especially https://github.com/tianon/gosu/blob/master/SECURITY.md)
=> Update to gosu 1.16

16/alpine3.17/Dockerfile, 16/alpine3.17/docker-entrypoint.sh, 16/alpine3.18/Dockerfile, 16/alpine3.18/docker-entrypoint.sh, 16/bullseye/Dockerfile, 16/bullseye/docker-entrypoint.sh, versions.json
=> Add postgres 16 beta1

12/bookworm/Dockerfile, 12/bullseye/Dockerfile, 13/bookworm/Dockerfile, 13/bullseye/Dockerfile, 14/bookworm/Dockerfile, 14/bullseye/Dockerfile, 15/bookworm/Dockerfile, 15/bullseye/Dockerfile, 16/bookworm/Dockerfile, 16/bullseye/Dockerfile, Dockerfile-debian.template
See https://github.com/tianon/gosu/releases/tag/1.17.
Similar to previously-merged move to 1.16 at https://github.com/docker-library/postgres/pull/1040.
=> update to gosu 1.17
